[tools]
node = { version = "22" }

[hooks]
postinstall = [
  "corepack enable",
  "pnpm install --frozen-lockfile", # TODO remove --frozen-lockfile if pnpm-lock.yaml is not included in this repo
]

[env]
_.path = "./node_modules/.bin"

[settings]
jobs = 8

# Required for hooks as of 2025.10
# https://mise.jdx.dev/hooks.html
experimental = true
